package com.example.demo.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.demo.Util.LocalDateConverter;
import lombok.*;

import java.time.LocalDate;

@DynamoDBTable(tableName = "users")
@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserEntity {

    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBAttribute(attributeName = "balance")
    private double balance;

    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @DynamoDBAttribute(attributeName = "createdAt")
    private LocalDate date=LocalDate.now();


    @DynamoDBIndexHashKey(globalSecondaryIndexName = "EmailIndex", attributeName = "email")
    public String getEmail() {
        return email;
    }
}
